<?php
echo '<h2>Array Walk => ';
$number = [1, 2, 3, 4, 5, 7, 8, 9];
array_walk($number, function (&$value) {
    return $value += 3;
});
print_r($number);
echo '</h2> <hr> <h2>Array Keys => ';
$Keys = array_keys($number, 6, true);
print_r($Keys);
echo '</h2><hr>';
echo '<h2>Array Values => ';
$list = ['name' => 'Ahmad', 'LastName' => 'Ahmadi', 'FotherName' => 'Rahman'];
$filtered = array_values($list);
print_r($filtered);
echo '</h2><hr>';
echo '<h2>Array Fliped => ';
$fliped = array_flip($list);
print_r($fliped);
echo '</h2> <hr> <h2> Array Unique => ';
$num = [1, 2, 3, 4, 5, 4, 6, 7, 8, 9, 8, 7];
$unique = array_unique($num);
print_r($unique);
echo '<h2> <hr> <h2> Array Deffered => ';
$deff = array_diff([1, 2, 3, 4], [1, 4]);
print_r($deff);
echo '</h2> <hr> <h2> Array Intersect => ';
$intersect = array_intersect([1, 2, 3, 4, 5], [2, 3, 4]);
print_r($intersect);
echo '</h2> <hr> <h2> Sort => ';
$newNum = [3, 4, 2, 1, 5, 7, 6, 8];
sort($newNum);
print_r($newNum);
echo '</h2> <hr> <h2> ASort => ';
$ASort = [3, 4, 2, 1, 5, 7, 6, 8];
asort($ASort);
print_r($ASort);
echo '</h2> <hr> <h2> KSort => ';
$KSort = [3, 4, 2, 1, 5, 7, 6, 8];
ksort($KSort);
print_r($KSort);
echo '</h2> <hr> <h2> USort => ';
$USort = [3, 4, 2, 1, 5, 7, 6, 8];
usort($USort, function ($a) {
    echo $a;
});
echo '</h2> <hr> <h2> In Array => ';
$numbers = [5, 6, 4, 7, 3, 8, 9, 9, 9, 7];
$IsExist = in_array(9, $numbers);
echo $IsExist;
echo '</h2> <hr> <h2> Array Search => ';
$arraySearch = array_search(7, $numbers);
print_r($arraySearch);
echo '</h2> <hr> <h2> Array Random => ';
$Random = [5, 6, 4, 7, 3, 8, 9, 9, 9, 7];
$Rand = array_rand($Random, 3);
print_r($Rand);
echo '</h2> <hr> <h2> Shuffle => ';
$Shuffle = [5, 6, 4, 7, 3, 8, 9, 9, 9, 7];
shuffle($Shuffle);
print_r($Shuffle);
